travis:
  secure:
    BINSTAR_TOKEN: sM6wSRIV+XSH767aNmHUu9Sx3P0TpStFr08iiML7QVBDvruJ0yCRkxSVQtQhUHzhQHivE7BGxnq2xhXIQFaKbPozxeCyRpyQs52M5ewOgm7jbtzOEN54UixxQyGXptz5IviIEt/xrjOzrem2WVB6NMrvpDj1FOOU2ILjcjDLhVMkH6KGFg3Qf8fm1emIoIUMwaXvwFezReSpKA022vRubYRxd3bGERkmuX2LX6v53R5fIgrG9NCF8gzv0B4EcZTQ4Guf5WGAGuvq73TJmX8wmBAKbKSP/3rJvkwSd0/MD9bKhLNH/xyBBXUdCzvFNQk/vPVbOJsG95y5FUXMMJ4fXeTaHwSG5bn3Gs8F2cS9xS79B1dEMsap/XJwOp54LZ/R+IfUYOM3NgSDPIyOZH8eEhW1j4XsACxHRxrlokZwWOY/vyfN/OdT5fdAjXjpfAC0JxeUab8fZnfWCSm3GezBsfrkfE8V6W/jy4OLL6FO8YO2xCt5r3jXqvFVKYIUWbA+F+mcDKZ46XtM4jJkuYwpkklX+NlL6Mn55bChuckAh6+oLLETFIZDNSEmxqG/j0UTIxX0Me3UgUzf2c4dTZWVc6gLIOcGVtdV8laicqVxBbQaQ4pDZt5Kbix5Hv4uTXtM/YhA0KCjKRnQDPkAl+weUj68cZsoB6LyMc53J5TcMwU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
