travis:
  secure:
    BINSTAR_TOKEN: ce+Bw60d6DCz24RGetfmfqlHBoVN7RnrKvDGpi49+Zg6UrUH+17EYUnuqZKY5cRfPTD2dK9cT3dCrndidyUNob1+VzRhKRoXuGGFkDPIo5PE6gIIn+TudkWiyGgAO157KQcfrj+ywtip0FlYxyVo5KFnUVSVJ6LJk1UiSxRuqbBPlzG+KK8f/HqTshICNPKJjUAUWh/1oPgtnqFLk0WHVowU7UPfaI5ZHXEOmvzzWnZAZSLIgQ3/NpaGfmLhWla4hcc/fvraXzKv1aumxpZUHQpb2UO/YWcgsjJJeqBEQ8eDrohwLRnQUUXl5ECLRQ46DZMc8KW/8An0gce0OAV6Bt5ymtjTO4sIwDa4LkCnithnL0RFOEViPbkDMoxsIzDsHHN5oKp5OH7hup+GHQx+RhqBuJJ1wbs6rDQt82tOvPayJbvNH6+aFaeajMowrtz6wyCy+SQCn39czr5lMWHBse2zn33z7bN01w00/IKnmbJTMuudXb1hbwKuCzgCL5Unmf/L7wDb83JlnK93tIxIwbwVpdSj3LPduuQjhP/g0Xo1NwKkhsT65IdVsNvej2P6IpEU/rPGZPoKcFV8Mi83FWUKJOBUvpbVJnBD0Ux/UGw0qYKEfp2MUx+limsXmsE3q712BrC/pprpcVh4jWdsSgYmqsoFQ+ZO7e8L1mRLD4A=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
