travis:
  secure:
    BINSTAR_TOKEN: rG+WBZSNnVx1+Qt55VoHGq0pdhtgp6ernoxDswntSTOVvunh8hla2WN8WvnLxfGQuJM97D1b68VgfkbORp7sceEDLskStIwh47T5dMULvfH17EQy2X/fdepwUdtN5s8MoL2D3+1djMDb303eJy5JSpopG22Mu65A6kM1zkQPq5y/8Rt4mB89Yix6yKfXYvMMU8ebLV4FSoBtQeGvRNZdvTS/zUmfTCvHp5drK+uaL5rXFRWbArYEZ8FkWHWierNvEiIvywkBUF6UGGo+BIo1iA6r73CPxmm7nS8m0k7zJgi4Nx9qRFF7pOd78jMUg7YMTavKQjd1Vy4732UWWDAuL33/RdOMIG3q90ZM6ByLNP4GPttUmkkVF2gqmuceoX1HAHgtBNfFCWYTojFTRA8mv/8A00J3Pywn3wKNunI9ov+dt5ltnXf9sNh8TShyW25t67XZv+v5X+Ogh308p1Zta/T++5YyrH5d4gPvw6c2TlIq4FdtxZoRBGgx+5gql9rVjklaNaGN0tlz1ik3ffJTiPkxB6Knek95fTA9C+5p9Ip06uXDFhe0ws6KA732iyILS0TNvwgFM4rI48igP27/zLQo36nOVqTt58TH1fMkg/QNIGEHwJST91aWsdFw1Wh/pbQFAtESqgOBOuJBXf0N4vwtzRyHkKeIKUfS5iSRQQc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
